
import java.io.File;

/**
 *
 * @author thaycacac
 */
public class Dialog extends javax.swing.JDialog {

    /**
     * Creates new form Dialog
     */
    ContactManager contactManager;
    StAXIterator staxIterator = new StAXIterator();

    public Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        contactManager = (ContactManager) parent;
        initComponents();
        if (contactManager.type.equals("Add")) {
            button.setText("Add New");
        } else {
            button.setText("Update");
            txtId.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 0).toString());
            txtName.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 1).toString());
            txtCompany.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 2).toString());
            txtEmai.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 3).toString());
            txtHomePhone.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 4).toString());
            txtOfficePhone.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 5).toString());
            txtMobilePhone.setText(contactManager.taskTable.getModel().getValueAt(contactManager.selectedRow, 6).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtEmai = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        txtOfficePhone = new javax.swing.JTextField();
        txtMobilePhone = new javax.swing.JTextField();
        button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("name");

        jLabel2.setText("company");

        jLabel3.setText("email");

        jLabel4.setText("home phone");

        jLabel5.setText("office phone");

        jLabel6.setText("mobile phone");

        jLabel7.setText("id");

        txtEmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmaiActionPerformed(evt);
            }
        });

        button.setText("Button");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOfficePhone)
                    .addComponent(txtMobilePhone)
                    .addComponent(button)
                    .addComponent(txtId)
                    .addComponent(txtCompany)
                    .addComponent(txtEmai)
                    .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.getAccessibleContext().setAccessibleName("tbOfficePhone");
        txtId.getAccessibleContext().setAccessibleName("tbId");
        txtId.getAccessibleContext().setAccessibleDescription("");
        txtName.getAccessibleContext().setAccessibleName("tbName");
        txtCompany.getAccessibleContext().setAccessibleName("tbCompany");
        txtEmai.getAccessibleContext().setAccessibleName("tbEmail");
        txtHomePhone.getAccessibleContext().setAccessibleName("tbHomePhone");
        txtMobilePhone.getAccessibleContext().setAccessibleName("tbMobilePhone");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        Phone phone = new Phone(txtMobilePhone.getText(), txtHomePhone.getText(), txtOfficePhone.getText());
        Contact contact = new Contact(Integer.parseInt(txtId.getText()), txtName.getText(), txtCompany.getText(), txtEmai.getText(), phone);
        if (contactManager.type.equals("Add")) {
            contactManager.contacts.add(contact);
        } else {
            txtId.setEditable(false);
            for (Contact temp : contactManager.contacts) {
                if (temp.getId() == contact.getId()) {
                    temp.setId(Integer.parseInt(txtId.getText()));
                    temp.setName(txtName.getText());
                    temp.setCompany(txtCompany.getText());
                    temp.setEmail(txtEmai.getText());
                    temp.getPhone().setHome(txtHomePhone.getText());
                    temp.getPhone().setOffice(txtOfficePhone.getText());
                    temp.getPhone().setMobile(txtMobilePhone.getText());
                }
            }
        }
        staxIterator.writeXML(contactManager.contacts, new File("contact.xml"));
        contactManager.load();
        dispose();
    }//GEN-LAST:event_buttonActionPerformed

    private void txtEmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog dialog = new Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtEmai;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMobilePhone;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOfficePhone;
    // End of variables declaration//GEN-END:variables
}
