const _products = [
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "1"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "2"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "3"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "4"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "5"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "6"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "7"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "8"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "9"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "10"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "11"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "12"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "13"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "14"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "15"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
  {
    category: {_text: "Ngôn Tình"},
    description: {_text: "Yêu trên từng ngón tay là tập truyện ngắn thứ ba c…động về tình người nên cô đã viết câu chuyện này."},
    id: {_text: "16"},
    image: {_text: "https://i.imgur.com/w8tIh07.jpg"},
    name: {_text: "Yêu Trên Từng Ngón Tay"},
    price: {_text: "75.5"},
    quantityInStock: {_text: "200"},
    sale: {_text: "true"},
  },
];

export default {
  getProducts(cb) {
    setTimeout(() => cb(_products), 100);
  },

  buyProducts(products, cb, errorCb) {
    setTimeout(() => {
      Math.random() > 0.5 || navigator.userAgent.indexOf("PhantomJS") > -1
        ? cb()
        : errorCb();
    }, 100);
  }
};
